export const Substates = {
    PENDING_PAYMENT: 'pending_payment',
    AWAITING_PAYMENT: 'awaiting_payment',
    TOO_SOON_FOR_FOLLOW_UP: 'too_soon_for_follow_up',
    BILLED: 'billed',
    APPEALED: 'appealed',
    HOSPITAL_REVIEW: 'hospital_review',
    SUCCESSFUL_COLLECTION: 'successful_collection',
    FAIL: 'fail',
    PAID: 'paid',
    REPORTED: 'reported',
    SELF_RETURNED: 'self_returned',
    MERGED: 'merged',
    UNKNOWN: 'unknown',
    NEW: 'new',
    FOLLOW_UP: 'follow_up',
    DENIED: 'denied',
    RETURNED: 'returned',
    BILLABLE: 'billable',
    SELF_PAY: 'self_pay',
    ESCALATED: 'user_escalated'
};