exports.queries = `
    # Return a single acct
    facilityByID(_id: ID!): Facility
    facilityList(clientIDs: [ID!], status: Boolean!): [Facility]
`

exports.baseSchema = `
  type Facility {
    _id: ID!
    name: String!
    sftpPath: String
    allowedUsers: [String!] #TODO : User IDs type
    clientId: ID!
    Status: Boolean!
    createdAt: gqlDate!
    placementRules: PlacementRules
    fileId: String # ! What is this for?
    fileIds: [String]
    contacts: [FacilityContacts]
  }

  type PlacementRules {
    hasHeader: Boolean
    acctNum: String
    medNo: String
    admitDate: String
    dischrgDate: String
    ptType: String
    ptName: String
    fbDate: String
    other1: String
    other2: String
    activeInsCode: String
    acctBal: String
    facCode: String
    finClass: String
    insurances: [InsuranceRules]
  }

  type InsuranceRules {
    insName: String
    insCode: String
    insBal: String
    address1: String
    address2: String
    city: String
    state: String
    policy: String
    phone: String
  }

  type FacilityContacts {
    firstName: String
    lastName: String
    phone: String
    email: String
    contactType: String
    notes: String
  }
`