export const Substates = {
    PENDING_PAYMENT: 'pending_payment',
    AWAITING_PAYMENT: 'awaiting_payment',
    TOO_SOON_FOR_FOLLOW_UP: 'too_soon_for_follow_up',
    BILLED: 'billed',
    APPEALED: 'appealed',
    HOSPITAL_REVIEW: 'hospital_review',
    SUCCESSFUL_COLLECTION: 'successful_collection',
    FAIL: 'fail',
    PAID: 'paid',
    REPORTED: 'reported',
    SELF_RETURNED: 'self_returned',
    MERGED: 'merged',
    UNKNOWN: 'unknown',
    NEW: 'new',
    FOLLOW_UP: 'follow_up',
    DENIED: 'denied',
    RETURNED: 'returned',
    BILLABLE: 'billable',
    SELF_PAY: 'self_pay',
    ESCALATED: 'escalated'
}

export const LabelSubstates = {
    [Substates.PENDING_PAYMENT]: 'Pending Payment',
    [Substates.AWAITING_PAYMENT]: 'Awaiting Payment',
    [Substates.TOO_SOON_FOR_FOLLOW_UP]: 'Too soon for follow up',
    [Substates.BILLED]: 'Billed',
    [Substates.APPEALED]: 'Appealed',
    [Substates.HOSPITAL_REVIEW]: 'Hospital Review',
    [Substates.SUCCESSFUL_COLLECTION]: 'Successful Collection',
    [Substates.FAIL]: 'Fail',
    [Substates.PAID]: 'Paid',
    [Substates.REPORTED]: 'Reported',
    [Substates.SELF_RETURNED]: 'Self Returned',
    [Substates.MERGED]: 'Merged',
    [Substates.UNKNOWN]: 'Unknown',
    [Substates.NEW]: 'New',
    [Substates.FOLLOW_UP]: 'Follow-Up',
    [Substates.DENIED]: 'Denied (Why?)',
    [Substates.RETURNED]: 'Returned (to be returned)',
    [Substates.BILLABLE]: 'Billable',
    [Substates.SELF_PAY]: 'Self-pay',
    [Substates.ESCALATED]: 'Escalated'
}